import { Inter,Jost,Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });
const jost = Jost({ subsets: ["latin"] });
const outfit = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <div className="flex flex-col max-w-[1440px] items-center ">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
